# Generated by Django 4.2.1 on 2023-09-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=-1)),
                ('attr_type', models.CharField(max_length=12)),
                ('help_text', models.TextField()),
                ('rules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('order', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='QObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_room', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=50)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edit.metaattr')),
                ('qobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edit.qobject')),
            ],
        ),
        migrations.AddField(
            model_name='metaattr',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edit.metapage'),
        ),
    ]
