# Generated by Django 4.2.1 on 2023-09-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaattr',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metapage',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metapage',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metapage',
            name='items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metapage',
            name='rooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metaattr',
            name='attr_type',
            field=models.CharField(choices=[('id', 'id string'), ('str', 'short string'), ('int', 'integer'), ('flg', 'boolean flag'), ('txt', 'text'), ('flt', 'float'), ('obj', 'object'), ('chc', 'choice'), ('scr', 'script'), ('say', 'string array'), ('rgx', 'regular expression'), ('gdr', 'gender'), ('dir', 'direction')], max_length=3),
        ),
    ]
