# Generated by Django 4.2.1 on 2023-09-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0002_metaattr_advanced_metapage_advanced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapage',
            name='rules',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metaattr',
            name='attr_type',
            field=models.CharField(choices=[('id', 'id string'), ('str', 'short string'), ('int', 'integer'), ('flg', 'boolean flag'), ('txt', 'text'), ('flt', 'float'), ('obj', 'object'), ('chc', 'choice'), ('scr', 'script'), ('say', 'string array'), ('rgx', 'regular expression'), ('gdr', 'gender'), ('dir', 'direction'), ('btn', 'button')], max_length=3),
        ),
    ]
