# Generated by Django 4.2.1 on 2023-10-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0003_metapage_rules_alter_metaattr_attr_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qobject',
            name='name',
        ),
        migrations.AlterField(
            model_name='metaattr',
            name='attr_type',
            field=models.CharField(choices=[('id', 'id string'), ('str', 'short string'), ('int', 'integer'), ('cbx', 'boolean flag'), ('txt', 'text'), ('obj', 'object'), ('itm', 'itm'), ('loc', 'location'), ('chc', 'choice'), ('scr', 'script'), ('say', 'string array'), ('rgx', 'regular expression'), ('gdr', 'gender'), ('dir', 'direction'), ('btn', 'button')], max_length=3),
        ),
    ]
