# Generated by Django 4.2.1 on 2023-11-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0004_remove_qobject_name_alter_metaattr_attr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qobject',
            name='name',
            field=models.CharField(default='anom', max_length=50),
            preserve_default=False,
        ),
    ]
