# Generated by Django 4.2.1 on 2023-11-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0005_qobject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qobject',
            name='is_room',
        ),
        migrations.AddField(
            model_name='metaattr',
            name='category',
            field=models.CharField(default='room', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qobject',
            name='category',
            field=models.CharField(default='room', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metaattr',
            name='attr_type',
            field=models.CharField(max_length=3),
        ),
    ]
