# Generated by Django 4.2.1 on 2023-11-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0006_remove_qobject_is_room_metaattr_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaattr',
            name='category',
            field=models.CharField(default='item', max_length=4),
        ),
        migrations.AlterField(
            model_name='qobject',
            name='category',
            field=models.CharField(default='item', max_length=4),
        ),
    ]
