# Generated by Django 4.2.1 on 2023-11-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0007_alter_metaattr_category_alter_qobject_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metapage',
            old_name='items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='metapage',
            old_name='rooms',
            new_name='room',
        ),
        migrations.AddField(
            model_name='metapage',
            name='sttg',
            field=models.BooleanField(default=False),
        ),
    ]
