# Generated by Django 4.2.1 on 2023-11-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0008_rename_items_metapage_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metapage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='metapage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='metapage',
            name='sttg',
        ),
        migrations.AddField(
            model_name='metapage',
            name='category',
            field=models.CharField(default='item', max_length=4),
        ),
    ]
