# Generated by Django 4.2.1 on 2023-11-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0009_remove_metapage_item_remove_metapage_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapage',
            name='help_link',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qattr',
            name='value',
            field=models.TextField(),
        ),
    ]
