# Generated by Django 4.2.1 on 2023-11-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0010_metapage_help_link_alter_qattr_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapage',
            name='params',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='metapage',
            name='return_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
