# Generated by Django 4.2.1 on 2023-11-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0011_metapage_params_metapage_return_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metapage',
            name='advanced',
        ),
    ]
