# Generated by Django 4.2.1 on 2023-11-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0012_remove_metapage_advanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapage',
            name='alias',
            field=models.CharField(default='alias', max_length=12),
            preserve_default=False,
        ),
    ]
