# Generated by Django 4.2.1 on 2023-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0014_metapage_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaattr',
            name='options_as_string',
            field=models.TextField(default=''),
        ),
    ]
