# Generated by Django 4.2.1 on 2023-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0015_metaattr_options_as_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaattr',
            name='params',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='metaattr',
            name='return_type',
            field=models.CharField(default='', max_length=12),
        ),
    ]
