# Generated by Django 4.2.1 on 2023-12-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0017_alter_metaattr_params_alter_metaattr_return_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='qobject',
            name='qgame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edit.qgame'),
        ),
    ]
