# Generated by Django 4.2.1 on 2023-12-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0018_qgame_qobject_qgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='qgame',
            name='subversion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
