# Generated by Django 5.0.3 on 2024-04-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0022_itemtoitemlinks_link_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtoitemlinks',
            old_name='npc',
            new_name='primaryitem',
        ),
        migrations.RenameField(
            model_name='itemtoitemlinks',
            old_name='item',
            new_name='secondaryitem',
        ),
    ]
