# Generated by Django 5.0.3 on 2024-04-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0024_rename_primaryitem_itemtoitemlinks_primaryobject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtoitemlinks',
            old_name='primaryobject',
            new_name='primary_object',
        ),
        migrations.RenameField(
            model_name='itemtoitemlinks',
            old_name='secondaryobject',
            new_name='secondary_object',
        ),
    ]
